substitutions:
  name: kitchen

esphome:
  name: fan-${name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
api:
ota:
  platform: esphome

mcp23008:
  - id: "mcp23008_hub"
    address: 0x20

i2c:
  sda: GPIO1 # Tx Blue
  scl: GPIO3 # Rx Green
  # scan: true

binary_sensor:
  - platform: gpio
    id: button1
    filters:
      - delayed_on_off: 100ms
    pin:
      mcp23xxx: mcp23008_hub
      number: 0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - if:
            condition:
              and:
                - lambda: "return id(speed).state == 1;"
                - switch.is_on: master
            then:
              - switch.turn_off: master
            else:
              - number.set:
                  id: speed
                  value: 1
              - switch.turn_on: master

  - platform: gpio
    id: button2
    filters:
      - delayed_on_off: 100ms
    pin:
      mcp23xxx: mcp23008_hub
      number: 1
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - if:
            condition:
              and:
                - lambda: "return id(speed).state == 2;"
                - switch.is_on: master
            then:
              - switch.turn_off: master
            else:
              - number.set:
                  id: speed
                  value: 2
              - switch.turn_on: master

  - platform: gpio
    id: button3
    filters:
      - delayed_on_off: 100ms
    pin:
      mcp23xxx: mcp23008_hub
      number: 2
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - if:
            condition:
              and:
                - lambda: "return id(speed).state == 3;"
                - switch.is_on: master
            then:
              - switch.turn_off: master
            else:
              - number.set:
                  id: speed
                  value: 3
              - switch.turn_on: master

number:
  - platform: template
    name: Fan ${name} speed
    id: speed
    icon: mdi:fan
    update_interval: never
    optimistic: true
    min_value: 1
    max_value: 3
    initial_value: 1
    step: 1
    set_action:
      - if:
          condition:
            - switch.is_on: master
          then:
            - lambda: >-
                if (x == 1) {return id(relay1).turn_on();}
            - lambda: >-
                if (x == 2) {return id(relay2).turn_on();}
            - lambda: >-
                if (x == 3) {return id(relay3).turn_on();}

switch:
  - platform: template
    id: master
    icon: mdi:fan
    name: Fan ${name} master
    optimistic: true
    on_turn_on:
      then:
        - lambda: >-
            if (id(speed).state == 1) {return id(relay1).turn_on();}
        - lambda: >-
            if (id(speed).state == 2) {return id(relay2).turn_on();}
        - lambda: >-
            if (id(speed).state == 3) {return id(relay3).turn_on();}
    on_turn_off:
      - lambda: "id(relay1).turn_off();"
      - lambda: "id(relay2).turn_off();"
      - lambda: "id(relay3).turn_off();"

  - platform: gpio
    id: internal_relay
    pin: GPIO12

  - platform: gpio
    id: relay1
    pin:
      mcp23xxx: mcp23008_hub
      number: 5
      mode: OUTPUT
      inverted: true
    interlock: &interlock_group [relay1, relay2, relay3]
    interlock_wait_time: 250ms
    on_turn_on:
      - switch.turn_on: internal_relay
      - number.set:
          id: speed
          value: 1
    on_turn_off:
      - switch.turn_off: internal_relay

  - platform: gpio
    id: relay2
    pin:
      mcp23xxx: mcp23008_hub
      number: 6
      mode: OUTPUT
      inverted: true
    interlock: *interlock_group
    interlock_wait_time: 250ms
    on_turn_on:
      - number.set:
          id: speed
          value: 2

  - platform: gpio
    id: relay3
    pin:
      mcp23xxx: mcp23008_hub
      number: 7
      mode: OUTPUT
      inverted: true
    interlock: *interlock_group
    interlock_wait_time: 250ms
    on_turn_on:
      - number.set:
          id: speed
          value: 3

status_led:
  pin:
    number: GPIO13
    inverted: yes
